todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    change_task_status,
    TagCreateView,
    TagsListView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="tasks"),
    path("create-task/", TaskCreateView.as_view(), name="create_task"),
    path("tasks/<int:pk>/change/", change_task_status, name="change-status"),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="update-task"),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="delete-task"),
    path("create-tag/", TagCreateView.as_view(), name="create_tag"),
    path("tags/", TagsListView.as_view(), name="tags"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="update-tag"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="delete-tag"),

]

app_name = "todo_list"

todo_list/models.py
from django.db import models


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-creation"]

    def __str__(self):
        return (
            f"{self.content} (creation - {self.creation}, "
            f"deadline - {self.deadline}), "
            f"is done - {self.is_done}"
        )

todo_list/forms.py
from django import forms

from todo_list.models import Tag, Task


class TagForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"


class TagSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name..."
            }
        )
    )


class TaskSearchForm(forms.Form):
    content = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name..."
            }
        )
    )

todo_list/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect

from todo_list.forms import TagForm, TagSearchForm, TaskSearchForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    queryset = Task.objects.all()
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        content = self.request.GET.get("content", "")

        context["task_search_form"] = TaskSearchForm(initial={
            "content": content
        })

        return context

    def get_queryset(self):
        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                content__icontains=form.cleaned_data["content"]
            )
        return self.queryset


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TagForm
    success_url = reverse_lazy("todo_list:tasks")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TagForm
    success_url = reverse_lazy("todo_list:tasks")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:tasks")


def change_task_status(request, pk: int):
    task = Task.objects.get(pk=pk)

    task.is_done = not task.is_done
    task.save()

    return redirect(reverse_lazy("todo_list:tasks"))


class TagsListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    queryset = Tag.objects.all()
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["tag_search_form"] = TagSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        form = TagSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return self.queryset


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tags")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tags")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tags")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link"> <<< </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link"> >>> </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_list:tasks' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tags' %}">All tags</a></li>
</ul>

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:tags' %}" class="btn btn-secondary">Back to tags</a>
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'todo_list:tags' %}" class="btn btn-secondary">Back to tags</a>
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tags list
    <a href="{% url 'todo_list:create_tag' %}" class="btn btn-primary link-to-page float-right">
      Create tag
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
      {{ tag_search_form|crispy }}
      <input type="submit" value="🔍✨" class="btn btn-info">
  </form>
    <br>
  {% if tag_list %}

  {% for tag in tag_list %}
      {{ tag.name }}
      <a href="{% url 'todo_list:update-tag' pk=tag.id %}" class="btn btn-primary btn-sm float-right">Update</a>
      <a style="margin-right: 5px" href="{% url 'todo_list:delete-tag' pk=tag.id %}" class="btn btn-danger btn-sm float-right">Delete</a>
      <hr>
  {% endfor %}

  {% else %}
    <p>There are no tag in tags list</p>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:tasks' %}" class="btn btn-secondary">Back to TODO's</a>
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'todo_list:tasks' %}" class="btn btn-secondary">Back to TODO's</a>
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tasks list
    <a href="{% url 'todo_list:create_task' %}" class="btn btn-primary link-to-page float-right">
      Create task
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
      {{ task_search_form|crispy }}
      <input type="submit" value="🔍✨" class="btn btn-info">
  </form>
  {% if task_list %}
    {% for task in task_list %}
      <div>
          <a href="{% url 'todo_list:update-task' pk=task.id %}"
             class="btn btn-primary btn-sm float-right">Update</a>
          <a style="margin-right: 5px"
             href="{% url 'todo_list:delete-task' pk=task.id %}"
             class="btn btn-danger btn-sm float-right">Delete</a>
          <h4>
            {{ task.content }}
          </h4>
          <h6>
              {% if task.is_done %}
                  <div style="color: limegreen" >Done      <a href="{% url 'todo_list:change-status' pk=task.id %}" class="btn btn-secondary btn-sm">Undo</a></div>

              {% else %}
                  <div style="color: red" >Not done      <a href="{% url 'todo_list:change-status' pk=task.id %}" class="btn btn-info btn-sm">Complete</a></div>
              {% endif %}
          </h6>
          Created at: {{ task.creation }}
          <br>
          Deadline:
          {% if task.deadline %}{{ task.deadline }}{% else %}this task has not deadline {% endif %}
          <p>
              Tags:
              {% for tag in task.tags.all %}
                  {{ tag }}
              {% endfor %}
          </p>

          <hr>

      </div>
    {% endfor %}

  {% else %}
    <p>There are no task in todo list</p>
  {% endif %}
{% endblock %}